name: Build Ariachi
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        uses: Randomblock1/theos-action@v1
      - name: Compile
        run: |
          unzip AriachiClient.zip -d build/
          cd build
          echo '{"Filter" = {"Bundles" = ("com.mojang.minecraftpe");};}' > AriachiClient.plist
          make package FINALPACKAGE=1 ARCHS="arm64 arm64e"
      - name: Extract Dylib
        run: |
          mkdir -p final_output
          find build/.theos/obj -name "*.dylib" -exec cp {} final_output/ \;
      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: Ariachi-Direct-Dylib
          path: final_output/*.dylib
