name: Build Ariachi
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        uses: Randomblock1/theos-action@v1
      - name: Compile
        run: |
          unzip AriachiClient.zip -d build/
          cd build
          echo '{"Filter" = {"Bundles" = ("com.mojang.minecraftpe");};}' > AriachiClient.plist
          make package FINALPACKAGE=1 ARCHS="arm64 arm64e"
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: AriachiClient-Package
          path: |
            build/packages/*.deb
            build/.theos/obj/debug/*.dylib
